version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: symfony_timelesslibrary
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://root:root@db:3306/timelesslibrary"
    depends_on:
      - db
    networks:
      - dev

  db:
    image: mysql:8.0
    container_name: db_timelesslibrary
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timelesslibrary
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:5.1.3
    container_name: phpmyadmin_timelesslibrary
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
       MYSQL_ROOT_PASSWORD: root          # Mot de passe pour l'utilisateur root
       MYSQL_DATABASE: timelesslibrary    # Nom de la base de données
    volumes:
    - db_data:/var/lib/mysql
    networks:
      - dev

networks:
  dev:

volumes:
  db_data:

